In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [13]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [4]:
iris_data = pd.read_csv('/kaggle/input/iris/Iris.csv')

In [5]:
print("\n========= First 5 rows ===========")
print(iris_data.head())
print("-------------------------------------")
print(iris_data.info())
print("\n===================================")


========= First 5 rows ===========
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
-------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: 

In [6]:
X = iris_data.drop("Species", axis=1)
Y = iris_data["Species"]

In [7]:
Y_numeric = pd.Categorical(Y).codes

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_numeric, test_size=0.2, random_state=40)

In [9]:
model = LogisticRegression(random_state=120)
model.fit(X_train, Y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=120)

In [10]:
predictions = model.predict(X_test)

In [11]:
accuracy = accuracy_score(Y_test, predictions)
classification_rep = classification_report(Y_test, predictions)

In [12]:
print(f"\n========= Model Evaluation ==========")
print(f"Accuracy of the model: {accuracy:.4f}")
print("\n========= Predictions ===========")
print(predictions)
print("\n========= Classification Report ===========")
print(classification_rep)
print("===========================================")


========= Model Evaluation ==========
Accuracy of the model: 1.0000

========= Predictions ===========
[0 1 2 2 1 2 1 1 1 0 1 0 0 2 1 2 2 2 1 1 2 2 1 0 1 0 0 2 0 1]

========= Classification Report ===========
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [14]:
model = KNeighborsClassifier()
model.fit(X_train, Y_train)

KNeighborsClassifier()

In [15]:
predictions = model.predict(X_test)

In [17]:
accuracy = accuracy_score(Y_test, predictions)
classification_rep = classification_report(Y_test, predictions)

In [18]:
print(f"\n========= Model Evaluation ==========")
print(f"Accuracy of the model: {accuracy:.4f}")
print("\n========= Predictions ===========")
print(predictions)
print("\n========= Classification Report ===========")
print(classification_rep)
print("===========================================")


========= Model Evaluation ==========
Accuracy of the model: 1.0000

========= Predictions ===========
[0 1 2 2 1 2 1 1 1 0 1 0 0 2 1 2 2 2 1 1 2 2 1 0 1 0 0 2 0 1]

========= Classification Report ===========
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [19]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [20]:
predictions = model.predict(X_test)

In [22]:
accuracy = accuracy_score(Y_test, predictions)
classification_rep = classification_report(Y_test, predictions)

In [23]:
print(f"\n========= Model Evaluation ==========")
print(f"Accuracy of the model: {accuracy:.4f}")
print("\n========= Predictions ===========")
print(predictions)
print("\n========= Classification Report ===========")
print(classification_rep)
print("===========================================")


========= Model Evaluation ==========
Accuracy of the model: 1.0000

========= Predictions ===========
[0 1 2 2 1 2 1 1 1 0 1 0 0 2 1 2 2 2 1 1 2 2 1 0 1 0 0 2 0 1]

========= Classification Report ===========
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

